language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-1-003177
before_script:
  - chmod a+x ./travis-build.sh
  - chmod a+x ./travis-post-build.sh
  - chmod a+x ./run-tests.sh
script:
  - ./travis-build.sh
  - ./run-tests.sh
  - ./travis-post-build.sh