language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-1-003177
before_script:
  - chmod a+x ./travis-build.sh
  - chmod a+x ./run-tests.sh
script:
  - ./travis-build.sh
  - ./run-tests.sh
  - curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "$TRAVIS_BRANCH"}' -X POST https://registry.hub.docker.com/u/noordwind/coolector.api/trigger/$DOCKER_HUB_WEBHOOK_TOKEN/